name: offline_translator_app
description: Offline multilingual voice translator
publish_to: 'none' # Remove this line if you intent to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Matched from README

dependencies:
  flutter:
    sdk: flutter

  # For storing simple key-value pairs (like setup completion flag)
  shared_preferences: ^2.0.15 # Matched from README

  # For searchable dropdown, potentially for voice profiles or language selection
  dropdown_search: ^5.0.2 # Matched from README

  # Cupertino icons are commonly used with Flutter
  cupertino_icons: ^1.0.2

  # For accessing device paths (e.g., for storing/accessing voice profiles)
  path_provider: ^2.0.11 # Useful for voice profiles, now uncommented

  # For requesting permissions (e.g., storage for voice profiles)
  permission_handler: ^10.2.0 # Added for managing permissions

  # For picking files (e.g., audio input)
  # file_picker: ^5.2.5 # Optional, if audio file input is implemented

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Recommended for code analysis

flutter:
  uses-material-design: true

  assets:
    # Paths to AI models, as specified in README
    - assets/models/whisper/
    - assets/models/indictrans/
    - assets/models/yourtts/
    # If you have other assets like images or fonts, list them here
    # - assets/images/logo.png
    # - assets/fonts/MyCustomFont.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
